DROP TABLE SYSTEM;
CREATE MEMORY TABLE SYSTEM(VERSION INTEGER NOT NULL,LAST_MODIFICATION_MILLIS BIGINT,LAST_MODIFICATION_SK_WEEK INTEGER,LAST_MODIFICATION_SK_DAY INTEGER,CHECK_YOUTH_TEAM_ID BOOLEAN,CHECK_COUNTRIES BOOLEAN, CHECK_UPDATE_DB BOOLEAN, REPAIR_COACHES BOOLEAN, CHECK_TRANSFERS BOOLEAN, TEAM_ID INT);
INSERT INTO system VALUES (0, 0, 0, 0, false, false, true, false, true, 0);
UPDATE SYSTEM SET VERSION = 16;
