UPDATE player SET exists_in_sokker = 0 where exists_in_sokker <> 2;
ALTER TABLE player ADD COLUMN height INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE player_archive ADD COLUMN height INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE junior ADD COLUMN formation INTEGER DEFAULT -1 NOT NULL;
ALTER TABLE junior_skills ADD COLUMN age INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE system ADD COLUMN COMPLETE_JUNIORS_AGE BOOLEAN;
UPDATE SYSTEM SET COMPLETE_JUNIORS_AGE = TRUE;
UPDATE SYSTEM SET VERSION = 24;