CREATE ALIAS DATE_TIME FOR "pl.pronux.sokker.model.Date.dateTimeToMillis";
ALTER TABLE club ADD COLUMN image_path VARCHAR;
ALTER TABLE player_skills ADD COLUMN millis BIGINT;
UPDATE player_skills SET millis = DATE_TIME((select date from player_skills as s WHERE s.id_skill = player_skills.id_skill),(select time from player_skills as s WHERE s.id_skill = player_skills.id_skill));
ALTER TABLE player_skills DROP COLUMN date;
ALTER TABLE player_skills DROP COLUMN time;
ALTER TABLE arena ADD COLUMN millis BIGINT;
UPDATE arena SET millis = DATE_TIME((select date from arena as s WHERE s.id = arena.id),(select time from arena as s WHERE s.id = arena.id));
ALTER TABLE arena DROP COLUMN date;
ALTER TABLE arena DROP COLUMN time;
ALTER TABLE club_arena_name ADD COLUMN millis BIGINT;
UPDATE club_arena_name SET millis = DATE_TIME((select date from club_arena_name as s WHERE s.id_data = club_arena_name.id_data),(select time from club_arena_name as s WHERE s.id_data = club_arena_name.id_data));
ALTER TABLE club_arena_name DROP COLUMN date;
ALTER TABLE club_arena_name DROP COLUMN time;
ALTER TABLE club_data_fanclub ADD COLUMN millis BIGINT;
UPDATE club_data_fanclub SET millis = DATE_TIME((select date from club_data_fanclub as s WHERE s.id_data = club_data_fanclub.id_data),(select time from club_data_fanclub as s WHERE s.id_data = club_data_fanclub.id_data));
ALTER TABLE club_data_fanclub DROP COLUMN date;
ALTER TABLE club_data_fanclub DROP COLUMN time;
ALTER TABLE club_data_money ADD COLUMN millis BIGINT;
UPDATE club_data_money SET millis = DATE_TIME((select date from club_data_money as s WHERE s.id_data = club_data_money.id_data),(select time from club_data_money as s WHERE s.id_data = club_data_money.id_data));
ALTER TABLE club_data_money DROP COLUMN date;
ALTER TABLE club_data_money DROP COLUMN time;
ALTER TABLE club_name ADD COLUMN millis BIGINT;
UPDATE club_name SET millis = DATE_TIME((select date from club_name as s WHERE s.id_data = club_name.id_data),(select time from club_name as s WHERE s.id_data = club_name.id_data));
ALTER TABLE club_name DROP COLUMN date;
ALTER TABLE club_name DROP COLUMN time;
ALTER TABLE junior_skills ADD COLUMN millis BIGINT;
UPDATE junior_skills SET millis = DATE_TIME((select date from junior_skills as s WHERE s.id_skill = junior_skills.id_skill),(select time from junior_skills as s WHERE s.id_skill = junior_skills.id_skill));
ALTER TABLE junior_skills DROP COLUMN date;
ALTER TABLE junior_skills DROP COLUMN time;
ALTER TABLE training ADD COLUMN millis BIGINT;
UPDATE training SET millis = DATE_TIME((select date from training as s WHERE s.id_training = training.id_training),(select time from training as s WHERE s.id_training = training.id_training));
ALTER TABLE training DROP COLUMN date;
ALTER TABLE training DROP COLUMN time;
ALTER TABLE note ADD COLUMN millis BIGINT;
UPDATE note SET millis = DATE_TIME((select date from note as s WHERE s.id_note = note.id_note),(select time from note as s WHERE s.id_note = note.id_note));
ALTER TABLE note DROP COLUMN date;
ALTER TABLE note DROP COLUMN time;
ALTER TABLE note ADD COLUMN alert_millis BIGINT;
UPDATE note SET alert_millis = DATE_TIME((select alert_date from note as s WHERE s.id_note = note.id_note),(select alert_time from note as s WHERE s.id_note = note.id_note));
ALTER TABLE note DROP COLUMN alert_date;
ALTER TABLE note DROP COLUMN alert_time;
UPDATE note SET alert_millis = null WHERE alert_millis = -1;
ALTER TABLE note ADD COLUMN mod_millis BIGINT;
UPDATE note SET mod_millis = DATE_TIME((select mod_date from note as s WHERE s.id_note = note.id_note),(select mod_time from note as s WHERE s.id_note = note.id_note));
ALTER TABLE note DROP COLUMN mod_date;
ALTER TABLE note DROP COLUMN mod_time;
UPDATE system SET version = 4;
