ALTER TABLE system ADD COLUMN check_youth_team_id BOOLEAN;
ALTER TABLE system ADD COLUMN check_countries BOOLEAN;
ALTER TABLE system ADD COLUMN check_update_db BOOLEAN;
CREATE TABLE COUNTRIES(COUNTRY_ID INTEGER NOT NULL,NAME VARCHAR,CURRENCY_NAME VARCHAR,CURRENCY_RATE DOUBLE,CONSTRAINT COUNTRIES_PKEY PRIMARY KEY(COUNTRY_ID));
CREATE TABLE REGIONS(REGION_ID INTEGER NOT NULL,COUNTRY_ID INTEGER,NAME VARCHAR,WEATHER INTEGER,CONSTRAINT REGIONS_PKEY PRIMARY KEY(REGION_ID),CONSTRAINT REGIONS_COUNTRY_ID_FKEY FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID) ON DELETE CASCADE);
UPDATE system SET check_countries = true;
UPDATE system SET check_youth_team_id = true;
UPDATE system SET check_update_db = true;
UPDATE system SET version = 9;